CREATE TABLE TRIP (
    TRIP_ID INT NOT NULL,
    START VARCHAR(50) NOT NULL,
    DESTINATION VARCHAR(50) NOT NULL,
    DISTANCE INT NOT NULL,
    PRICE INT NOT NULL,
    NUMBER_PF_PASSENGERS INT NOT NULL,
    DEPARTURE_TIME TIME NOT NULL,
    ADMIN VARCHAR(50) NOT NULL,
    PRIMARY KEY (TRIP_ID),
    FOREIGN KEY (ADMIN) REFERENCES ADMIN(ADMIN_ID)
);

CREATE TABLE ADMIN (
    ADMIN_ID VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PHONE_NUM VARCHAR(50) NOT NULL,
    PRIMARY KEY (ADMIN_ID)
);

CREATE TABLE TRANSACTION (
    TRANSACTION_ID INT NOT NULL,
    TRIP_ID INT NOT NULL,
    TIME TIME NOT NULL,
    PAYMENT_PROVIDER VARCHAR(50) NOT NULL,
    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP(TRIP_ID)
);

